// <auto-generated />
namespace TechBlogCMS.UI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class userChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201508111859307_userChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
